# This is the default format.
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:year/:month/:day/:title

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
# title : Blog
# tagline: Yup
# author :
#   name : Lucas Holmquist
#   email : lholmqui@redhat.com
#   github : lholmquist
#   twitter : sienaluke

title:            Blog
description:      Yup
disqus_shortname: shortname


# The production_url is only used when full-domain names are needed
# such as sitemap.txt
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.com, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url : http://lholmquist.github.com


# Owner/author information
owner:
  name:           Lucas Holmquist
  avatar:         avatar.jpg
  bio:            "This is my Bio. I Know. Interesting Stuff"
  email:          lholmqui@redhat.com
  # Social networking links used in footer. Update and remove as you like.
  twitter: sienaluke
  facebook:
  github: lholmquist
  stackexchange:
  linkedin:
  instagram:
  flickr:
  tumblr:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:

# Links to include in top navigation
# For external links add external: true
# links:
#   - title: Theme Setup
#     url: /theme-setup

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
pygments:    true
markdown:    kramdown
