apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lholmquist.github.com-old
  annotations:
    github.com/project-slug: lholmquist/lholmquist.github.com-old
spec:
  type: other
  lifecycle: unknown
  owner: user:default/guest
